module.exports = cookie = [
  {
    domain: '.facebook.com',
    expirationDate: 1729019654.182669,
    hostOnly: false,
    httpOnly: false,
    key: 'c_user',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value: '100087201477902',
    id: 1,
  },
  {
    domain: '.facebook.com',
    expirationDate: 1731091898.668197,
    hostOnly: false,
    httpOnly: true,
    key: 'datr',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value: 'sAUfZQGlwrEKy69CEUomTFm_',
    id: 2,
  },
  {
    domain: '.facebook.com',
    expirationDate: 1705260118.887136,
    hostOnly: false,
    httpOnly: true,
    key: 'fr',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value: '0CEBwkIzaY5Hfkkwb.AWX85Vvdo3iuzTkQ7qjMtPIXOyQ.BlLYuF.Az.AAA.0.0.BlLY1W.AWU_bpAEzZI',
    id: 3,
  },
  {
    domain: '.facebook.com',
    hostOnly: false,
    httpOnly: false,
    key: 'presence',
    path: '/',
    sameSite: 'unspecified',
    secure: true,
    session: true,
    storeId: '0',
    value: 'C%7B%22t3%22%3A%5B%5D%2C%22utc3%22%3A1697483865959%2C%22v%22%3A1%7D',
    id: 4,
  },
  {
    domain: '.facebook.com',
    expirationDate: 1732017346.134839,
    hostOnly: false,
    httpOnly: true,
    key: 'sb',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value: 'sAUfZWGSMw9PY4cdCAYJpy1d',
    id: 5,
  },
  {
    domain: '.facebook.com',
    expirationDate: 1698088921,
    hostOnly: false,
    httpOnly: false,
    key: 'wd',
    path: '/',
    sameSite: 'lax',
    secure: true,
    session: false,
    storeId: '0',
    value: '1312x644',
    id: 6,
  },
  {
    domain: '.facebook.com',
    expirationDate: 1729019654.182774,
    hostOnly: false,
    httpOnly: true,
    key: 'xs',
    path: '/',
    sameSite: 'no_restriction',
    secure: true,
    session: false,
    storeId: '0',
    value:
      '47%3ASwxRbfktMwrTOg%3A2%3A1696534481%3A-1%3A9890%3A%3AAcXk2sYIc_V74qZlqrdJ0lSaQtJ9_JIUZI_OfLwfroQ',
    id: 7,
  },
];
